<h1>Página Incial</h1>
<hr>
<p>Controlador: IndexController</p>
<p>Action: index</p>
<hr>
<h2>Formulário de login</h2>

<?php
// echo '<pre>';
// print_r($this->view->dados);
// echo'</pre>';
// exit;

?>

<div class="col-md-6 pt-4 pl-5 pr-5">
    <form method="post" action="/autenticar">
        <div class="row">
            <div class="col">
                <input type="text" name="email" class="form-control" placeholder="E-mail">
            </div>
            <div class="col">
                <input type="password" name="senha" class="form-control" placeholder="Senha">
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary mb-2">Entrar</button>
            </div>
        </div>

        <?php if ($this->view->login == 'erro') { ?>
            <div class="row">
                <div class="col">
                    <span class="text text-danger">*E-mail e ou senha inválido(s)</span>
                </div>
            </div>
        <?php } ?>
    </form>